
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Button factura;
	private global::Gtk.Entry subtotal1;
	private global::Gtk.Entry iva1;
	private global::Gtk.Entry total1;
	private global::Gtk.Entry p3;
	private global::Gtk.Entry p2;
	private global::Gtk.Label subtotal;
	private global::Gtk.Label producto3;
	private global::Gtk.Label total;
	private global::Gtk.Entry p1;
	private global::Gtk.Label producto2;
	private global::Gtk.Label producto1;
	private global::Gtk.Label iva;
	private global::Gtk.Button limpiar;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.factura = new global::Gtk.Button ();
		this.factura.CanFocus = true;
		this.factura.Name = "factura";
		this.factura.UseUnderline = true;
		this.factura.Label = global::Mono.Unix.Catalog.GetString ("FACTURAR");
		this.fixed1.Add (this.factura);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.factura]));
		w1.X = 41;
		w1.Y = 305;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.subtotal1 = new global::Gtk.Entry ();
		this.subtotal1.CanFocus = true;
		this.subtotal1.Name = "subtotal1";
		this.subtotal1.IsEditable = true;
		this.subtotal1.InvisibleChar = '●';
		this.fixed1.Add (this.subtotal1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.subtotal1]));
		w2.X = 212;
		w2.Y = 164;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.iva1 = new global::Gtk.Entry ();
		this.iva1.CanFocus = true;
		this.iva1.Name = "iva1";
		this.iva1.IsEditable = true;
		this.iva1.InvisibleChar = '●';
		this.fixed1.Add (this.iva1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.iva1]));
		w3.X = 212;
		w3.Y = 210;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.total1 = new global::Gtk.Entry ();
		this.total1.CanFocus = true;
		this.total1.Name = "total1";
		this.total1.IsEditable = true;
		this.total1.InvisibleChar = '●';
		this.fixed1.Add (this.total1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.total1]));
		w4.X = 212;
		w4.Y = 253;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.p3 = new global::Gtk.Entry ();
		this.p3.CanFocus = true;
		this.p3.Name = "p3";
		this.p3.IsEditable = true;
		this.p3.InvisibleChar = '●';
		this.fixed1.Add (this.p3);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.p3]));
		w5.X = 210;
		w5.Y = 102;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.p2 = new global::Gtk.Entry ();
		this.p2.CanFocus = true;
		this.p2.Name = "p2";
		this.p2.IsEditable = true;
		this.p2.InvisibleChar = '●';
		this.fixed1.Add (this.p2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.p2]));
		w6.X = 210;
		w6.Y = 56;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.subtotal = new global::Gtk.Label ();
		this.subtotal.Name = "subtotal";
		this.subtotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Subtotal");
		this.fixed1.Add (this.subtotal);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.subtotal]));
		w7.X = 73;
		w7.Y = 163;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.producto3 = new global::Gtk.Label ();
		this.producto3.Name = "producto3";
		this.producto3.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 3");
		this.fixed1.Add (this.producto3);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.producto3]));
		w8.X = 74;
		w8.Y = 105;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.total = new global::Gtk.Label ();
		this.total.Name = "total";
		this.total.LabelProp = global::Mono.Unix.Catalog.GetString ("Total");
		this.fixed1.Add (this.total);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.total]));
		w9.X = 74;
		w9.Y = 250;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.p1 = new global::Gtk.Entry ();
		this.p1.CanFocus = true;
		this.p1.Name = "p1";
		this.p1.IsEditable = true;
		this.p1.InvisibleChar = '●';
		this.fixed1.Add (this.p1);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.p1]));
		w10.X = 208;
		w10.Y = 19;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.producto2 = new global::Gtk.Label ();
		this.producto2.Name = "producto2";
		this.producto2.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 2");
		this.fixed1.Add (this.producto2);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.producto2]));
		w11.X = 74;
		w11.Y = 61;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.producto1 = new global::Gtk.Label ();
		this.producto1.Name = "producto1";
		this.producto1.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 1");
		this.fixed1.Add (this.producto1);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.producto1]));
		w12.X = 74;
		w12.Y = 21;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.iva = new global::Gtk.Label ();
		this.iva.Name = "iva";
		this.iva.LabelProp = global::Mono.Unix.Catalog.GetString ("IVA");
		this.fixed1.Add (this.iva);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.iva]));
		w13.X = 82;
		w13.Y = 202;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.limpiar = new global::Gtk.Button ();
		this.limpiar.CanFocus = true;
		this.limpiar.Name = "limpiar";
		this.limpiar.UseUnderline = true;
		this.limpiar.Label = global::Mono.Unix.Catalog.GetString ("LIMPIAR");
		this.fixed1.Add (this.limpiar);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.limpiar]));
		w14.X = 263;
		w14.Y = 301;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 424;
		this.DefaultHeight = 394;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.factura.Clicked += new global::System.EventHandler (this.OnFacturaClicked);
		this.limpiar.Clicked += new global::System.EventHandler (this.OnLimpiarClicked);
	}
}
